### ISSUE TITLE
retire cms, or add github oauth app

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/sola#1]
when this repo was moved from gitlab to github, authentication in the cms via gitlab broke as well.

on github, we cannot use an implicit grant oauth flow, so we need someone with permissions to install a oauth app on the `acdh-oeaw` github org. also, project team members need to create a github user account if they don't have one already, and be added as contributors to this repo.

otherwise, if the cms is not needed anymore anyway, we should just retrire it.

@dasch124 opinions?

**Comment by vronk** [comment]
The users came back now that they would like to update the information.
I am checking if it is one time or continuous
Depending on that, we would resurrect the CMS.
Then, I assume @dpancic could help you with the oauth app?

**Comment by stefanprobst** [comment]
we decided to re-active the cms - sign in at https://sola.acdh.oeaw.ac.at/admin/index.html
