### ISSUE TITLE
vertical spacing on small resolution screens

### ISSUE THREAD

**Issue by dasch124** [acdh-oeaw/sola#3]
On screens with less resolution the footer is glued at the bottom of the page eating up vertical screen space. This leads the "detail panel" of the selected entity (passage, person, work etc.) to shrink to an amount that even with scrolling the content is not readable any more. Would it be possible to avoid scrolling the detail panel and push the footer below it?

**Comment by stefanprobst** [comment]
what resolution are we talking about here? can you maybe post a screenshot?

**Comment by stefanprobst** [comment]
invalid. seems to be related to zoom
